dist: trusty
sudo: required
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '5'
install:
- npm install
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master